In [26]:
import numpy as np
import pandas as pd
import Recommenders as Recommenders

In [27]:
song_Df1 = pd.read_csv('triplets_file.csv')
song_Df1.head()

                                    user_id             song_id  listen_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1

In [28]:
song_Df2 = pd.read_csv('song_data.csv')
song_Df2.head()

,song_id,title,release,artist_name,year
0,SOQMMHC12AB0180CB8,Silent Night,Monster Ballads X-Mas,Faster Pussy cat,2003
1,SOVFVAK12A8C1350D9,Tanssi vaan,Karkuteillä,Karkkiautomaatti,1995
2,SOGTUKN12AB017F4F1,No One Could Ever,Butter,Hudson Mohawke,2006
3,SOBNYVR12A8C13558C,Si Vos Querés,De Culo,Yerba Brava,2003
4,SOHSBXH12A8C13B0DF,Tangle Of Aspens,Rene Ablaze Presents Winter Sessions,Der Mystic,0

In [29]:
# merge both the data into the single datafrme
song_Df = pd.merge(song_Df1,song_Df2.drop_duplicates(['song_id']),on='song_id',how='left')
song_Df.head()

,user_id,song_id,listen_count,title,release,artist_name,year
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999

In [30]:
# merging the song title and artisit name by using - 
song_Df['song'] = song_Df['title']+' - '+ song_Df['artist_name']
song_Df.head()

,user_id,song_id,listen_count,title,release,artist_name,year,song
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0,The Cove - Jack Johnson
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976,Entre Dos Aguas - Paco De Lucia
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007,Stronger - Kanye West
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005,Constellations - Jack Johnson
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999,Learn To Fly - Foo Fighters

In [31]:
song_Df = song_Df.head(10000)

In [32]:
song_Df['song']

0                             The Cove - Jack Johnson
1                     Entre Dos Aguas - Paco De Lucia
2                               Stronger - Kanye West
3                       Constellations - Jack Johnson
4                         Learn To Fly - Foo Fighters
                            ...
9995                 Show Me How To Live - Audioslave
9996                    Billy Liar - The Decemberists
9997    The Bachelor and the Bride - The Decemberists
9998               Red Right Ankle - The Decemberists
9999        Song for Myla Goldberg - The Decemberists
Name: song, Length: 10000, dtype: object

In [33]:
# comulative of sum count
song_grouped = song_Df.groupby(['song']).agg({'listen_count':'count'}).reset_index()
song_grouped.head()

                                    song  listen_count
0               #40 - DAVE MATTHEWS BAND             1
1                    & Down - Boys Noize             4
2            '97 Bonnie & Clyde - Eminem             2
3          'Round Midnight - Miles Davis             3
4  'Till I Collapse - Eminem / Nate Dogg             6

In [34]:
# grouped by sum in the persantage
grouped_sum = song_grouped['listen_count'].sum()
song_grouped['percentage'] = ((song_grouped['listen_count']) / grouped_sum)*100
song_grouped.sort_values(['listen_count','song'],ascending=[0,1])

,song,listen_count,percentage
3660,Sehr kosmisch - Harmonia,45,0.45
4678,Undo - Björk,32,0.32
5105,You're The One - Dwight Yoakam,32,0.32
1071,Dog Days Are Over (Radio Edit) - Florence + Th...,28,0.28
3655,Secrets - OneRepublic,28,0.28
...,...,...,...
5139,high fives - Four Tet,1,0.01
5140,in white rooms - Booka Shade,1,0.01
5143,paranoid android - Christopher O'Riley,1,0.01
5149,¿Lo Ves? [Piano Y Voz] - Alejandro Sanz,1,0.01
5150,Época - Gotan Project,1,0.01

In [35]:
# popularity recomandation engine 
#  music recomandation base on the popularity
pr = Recommenders.popularity_recommender_py() 
pr.create(song_Df,'user_id','song')
pr.recommend(song_Df['user_id'][5])

,user_id,song,score,Rank
3660,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Sehr kosmisch - Harmonia,45,1.0
4678,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Undo - Björk,32,2.0
5105,b80344d063b5ccb3212f76538f3d9e43d87dca9e,You're The One - Dwight Yoakam,32,3.0
1071,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Dog Days Are Over (Radio Edit) - Florence + Th...,28,4.0
3655,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Secrets - OneRepublic,28,5.0
4379,b80344d063b5ccb3212f76538f3d9e43d87dca9e,The Scientist - Coldplay,27,6.0
4712,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Use Somebody - Kings Of Leon,27,7.0
3476,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Revelry - Kings Of Leon,26,8.0
1387,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Fireflies - Charttraxx Karaoke,24,9.0
1862,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Horn Concerto No. 4 in E flat K495: II. Romanc...,23,10.0

In [36]:
# item simarity enigine 
# base on the user listening recomnade the song 
ir = Recommenders.item_similarity_recommender_py()
ir.create(song_Df,'user_id','song')

In [37]:
user_items = ir.get_user_items(song_Df['user_id'][100])

In [38]:
for user_item in user_items:
    print(user_item)

Undo - Björk
Dog Days Are Over (Radio Edit) - Florence + The Machine
High Life - Daft Punk
You're The One - Dwight Yoakam
Where Did You Sleep Last Night - Nirvana
Come As You Are - Nirvana
Hey_ Soul Sister - Train
Horn Concerto No. 4 in E flat K495: II. Romance (Andante cantabile) - Barry Tuckwell/Academy of St Martin-in-the-Fields/Sir Neville Marriner
Rhyme & Reason - DAVE MATTHEWS BAND
Sehr kosmisch - Harmonia
Someone Else's Arms - Mae
Cry For Help (Album Version) - Shinedown
Lady In Black - Ensiferum
For You (Amended/Radio Edit LP) - Staind
Fireflies - Charttraxx Karaoke
Secrets - OneRepublic
Esta Es Para Hacerte Féliz - Jorge Gonzalez
Revelry - Kings Of Leon
Marry Me - Train
OMG - Usher featuring will.i.am
Drop The World - Lil Wayne / Eminem
Ain't Misbehavin - Sam Cooke
Blow Me Away - Breaking Benjamin
Use Somebody - Kings Of Leon
Corn Bread - DAVE MATTHEWS BAND

In [39]:
ir.recommend(song_Df['user_id'][100])

No. of unique songs for the user: 25
no. of unique songs in the training set: 5151
Non zero values in cooccurence_matrix :11051

,user_id,song,score,rank
0,e006b1a48f466bf59feefed32bec6494495a4436,Lucky (Album Version) - Jason Mraz & Colbie Ca...,0.102113,1
1,e006b1a48f466bf59feefed32bec6494495a4436,Somebody To Love - Justin Bieber,0.093648,2
2,e006b1a48f466bf59feefed32bec6494495a4436,Just Dance - Lady GaGa / Colby O'Donis,0.093492,3
3,e006b1a48f466bf59feefed32bec6494495a4436,Alejandro - Lady GaGa,0.090891,4
4,e006b1a48f466bf59feefed32bec6494495a4436,Heartbreak Warfare - John Mayer,0.090690,5
5,e006b1a48f466bf59feefed32bec6494495a4436,Love Story - Taylor Swift,0.088481,6
6,e006b1a48f466bf59feefed32bec6494495a4436,The Scientist - Coldplay,0.085540,7
7,e006b1a48f466bf59feefed32bec6494495a4436,Bleed It Out [Live At Milton Keynes] - Linkin ...,0.079296,8
8,e006b1a48f466bf59feefed32bec6494495a4436,Bulletproof - La Roux,0.077164,9
9,e006b1a48f466bf59feefed32bec6494495a4436,The Only Exception (Album Version) - Paramore,0.076146,10

In [41]:
# give related song base on the words 
ir.get_similar_items(['Somebody To Love - Justin Bieber'])

no. of unique songs in the training set: 5151
Non zero values in cooccurence_matrix :600

  user_id                                               song     score  rank
0                                    U Smile - Justin Bieber  0.352941     1
1                                           Marry Me - Train  0.346154     2
2          Lucky (Album Version) - Jason Mraz & Colbie Ca...  0.321429     3
3                          Party In The U.S.A. - Miley Cyrus  0.291667     4
4             Eenie Meenie - Sean Kingston and Justin Bieber  0.277778     5
5                                   Sehr kosmisch - Harmonia  0.265306     6
6                                    Love Me - Justin Bieber  0.263158     7
7                                        Monster - Lady GaGa  0.263158     8
8          Pursuit Of Happiness (nightmare) - Kid Cudi / ...  0.260870     9
9          Teach Me How To Dougie - California Swag District  0.250000    10